const STRENGTH = 'STRENGTH'
const DEXTERITY = 'DEXTERITY'
const CONSTITUTION = 'CONSTITUTION'
const INTELLIGENCE = 'INTELLIGENCE'
const WISDOM = 'WISDOM'
const CHARISMA = 'CHARISMA'

const ABILITY_IDS = [
  STRENGTH,
  DEXTERITY,
  CONSTITUTION,
  INTELLIGENCE,
  WISDOM,
  CHARISMA
]

module.exports = {
  ABILITY_IDS
}
